# ASP.NET
# Build and test ASP.NET projects.

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Sync GitHub changes to Azure DevOps
- script: |
    # Set up the GitHub remote
    git remote add github https://github.com/Suraj2522/SelfFunded.git
    
    # Configure Git to use the stored credentials
    git config --global credential.helper store
    echo "https://Suraj2522:Paramount@13746@github.com" > ~/.git-credentials
    
    # Fetch changes from GitHub
    git fetch github
    
    # Merge changes from the main branch of GitHub
    git merge github/main --no-edit || echo "No changes to merge"
    
    # Push changes to Azure DevOps repository
    git push origin master || echo "No changes to push"
  displayName: 'Sync GitHub changes to Azure DevOps'
