using System;

namespace SelfFunded.Models
{
    public class PreAuth
    {
        public IntimationSheetInbound intimationSheetInbound;
        public long preAuthID { get; set; }

        public string? preAuthNumber { get; set; }
        public string? insuredName { get; set; }
        public string? gender { get; set; }
        public DateTime? dateOfBirth { get; set; }
        public string? age { get; set; }
        public string? policyNo { get; set; }
        public string? contactNo { get; set; }
        public string? cardNo { get; set; }
       // public bool? networkType { get; set; }
        public int? providerId { get; set; }
        public int? roomTypeId { get; set; }
        public int? srNo{ get; set; }
        
        public int? caseTypeId { get; set; }

        public string? doctorName { get; set; }
        public string? complaints { get; set; }
        public string? diagnosis { get; set; }
        public string? treatment { get; set; }
        public int insuranceIds { get; set; }
        public decimal? lengthOfStay { get; set; }
        public DateTime? treatmentDate { get; set; }
        public int? processingCurrencyId { get; set; }
        public int? finalPayableCurrencyId { get; set; }
        public int? createByUserId { get; set; }
        public DateTime? createDate { get; set; }
        public string? insuranceType { get; set; }
        public int? modifyByUserId { get; set; }
        public DateTime? modifyDate { get; set; }
        public char? recStatus { get; set; }
        public int? insuranceCompanyId { get; set; }
        public int? ailmentId { get; set; }
        public string? intimationNo { get; set; }
        public decimal? grossAmount { get; set; }
        public decimal? approvedAmount { get; set; }
        public decimal? rejectedAmount { get; set; }
        public decimal? netAmount { get; set; }
        public string? claimStatus { get; set; }
        public bool? refferedToIns { get; set; }
        public string? remarks { get; set; }
        public string? certificateNo { get; set; }
        public string? coPayType { get; set; }
        public decimal? coPayValue { get; set; }
        public decimal? coInsurance { get; set; }
        public int? previousPreAuthId { get; set; }
        public string? cancelRemarks { get; set; }
        public int? nationality { get; set; }
        public string? prefix { get; set; }
        public string? previousPreAuthNo { get; set; }
        public int? stageId { get; set; }
        public string? caseType { get; set; }
        public DateTime? dischargeDate { get; set; }
        public int? providerNo { get; set; }
        public string? providerName { get; set; }
        public string? countryCode { get; set; }
        public string? countryName { get; set; }
        public string? stateCode { get; set; }
        public string? stateName { get; set; }
        public string? cityCode { get; set; }
        public string? cityName { get; set; }
        public string? hospitalName { get; set; }
        public string? providerCategoryType { get; set; }
        public string? providerAddress1 { get; set; }
        public string? providerAddress2 { get; set; }
        public string? providerAddressArea { get; set; }
        public string? providerPincode { get; set; }
        public string? providerAreaCode { get; set; }
        public string? providerContactNo { get; set; }
        public string? providerFaxNo { get; set; }
        public string? providerEmailId { get; set; }
        public string? providerWebsite { get; set; }
        public DateTime? refferedToInsDate { get; set; }
        public string? locked { get; set; }
        public int? lockedBy { get; set; }
        public DateTime? lockDate { get; set; }
        public string? databaseType { get; set; }
        public string? oldProviderNO { get; set; }
        public string? oldProviderName { get; set; }
        public DateTime? mainPreAuthDate { get; set; }
        public int? overseasId { get; set; }
        public decimal? assistantCharges { get; set; }
        public int? approvedBy { get; set; }
        public DateTime? approvedDate { get; set; }
        public int? rejectedBy { get; set; }
        public DateTime? rejectedDate { get; set; }
        public int? assistantFeesCurrencyId { get; set; }
        public string? panNo { get; set; }
        public int? approvedRejectedBy { get; set; }
        public DateTime? approvedRejectedDate { get; set; }
        public int? providerRequestId { get; set; }
        public int? patientStatusId { get; set; }
        public string? patientStatus { get; set; }
        public string? timeOfAdmission { get; set; }
        public string? timeOfDischarge { get; set; }
        public decimal? negotiatedAmount { get; set; }
        public decimal? discountAmount { get; set; }
        public decimal? amountWithoutDeduction { get; set; }
        public DateTime? claimDate { get; set; }
        public int? claimById { get; set; }
        public int? dependentCode { get; set; }
        public DateTime? savingsDownloadedDate { get; set; }
        public int? savingsDownloadedBy { get; set; }
        public decimal? revisedAmount { get; set; }
        public int? payerId { get; set; }
        public string? payerName { get; set; }
        public string? hospitalEmailId { get; set; }
        public string? logNumber { get; set; }
        public string? memberEmailId { get; set; }
        public DateTime? caseReceiptDate { get; set; }
        public DateTime? fromDate { get; set; }
        public string? orderByCol { get; set; }

        public DateTime? toDate { get; set; }
        public DateTime? emailRespondDate { get; set; }
        public string? caseRemarks { get; set; }
        public int? intimationId { get; set; }
        public int? claimBenefitId { get; set; }
        public int? productId { get; set; }
        public int? planId { get; set; }
        public string? employeeCode { get; set; }
        public int? memberId { get; set; }
        public int? enrollmentId { get; set; }
        public bool? overrideAlert { get; set; }
        public int? groupPolicyId { get; set; }
        public bool? referredToProvider { get; set; }
        public int? phmCommentsId { get; set; }
        public string? phmCommentsOther { get; set; }
        public int? branchId { get; set; }
        public string? phsFIRNo { get; set; }
        public string? ewiseCheck { get; set; }
        public string? ewiseCheckRemarks { get; set; }
        public string? mouDiscountCheck { get; set; }
        public string? mouDiscountCheckRemarks { get; set; }
        public string? hospitalType { get; set; }
        public int? insuranceStatusId { get; set; }
        public int? loginTypeId { get; set; }
        public decimal? tariffDeduction { get; set; }
        public int? hospitalTypeId { get; set; }
        public int? preAuthLogId { get; set; }
        public string? loginType { get; set; }
        public string? referToInsuranceYesNo { get; set; }
        public decimal? rejectedAmount_Copy { get; set; }
        //public int? isDeleted { get; set; }
        //public DateTime? deletedDate { get; set; }
        //public string? procedureIDs { get; set; }
        //public string? remarksIDs { get; set; }
        //public string? fileUploadIDs { get; set; }
        //public string? exclusionIDs { get; set; }
        //public string? tempDiagnosisIds { get; set; }
        //public string? tempRemarksIds { get; set; }
        //public string? tempNotesId { get; set; }
        //public string? preAuthRemarksId { get; set; }
        //public int? isDeficiencyRetrieved { get; set; }
        //public string? medicalOpinionIds { get; set; }

        public string? insuranceCompany { get; set; }
        public string? roomType { get; set; }
        //public string? providerName { get; set; }
        public string? ailmentName { get; set; }
        //public int preAuthID { get; set; }
        //public string? preAuthNumber { get; set; }
        //public string? insuredName { get; set; }
        //public string? gender { get; set; }
        //public string? dateOfBirth { get; set; }
        //public int age { get; set; }
        //public string? policyNo { get; set; }
        //public string? contactNo { get; set; }
        //public string? cardNo { get; set; }
        public string? networkType { get; set; }
        //public int providerId { get; set; }
        //public int roomTypeId { get; set; }
        //public string? doctorName { get; set; }
        //public string? complaints { get; set; }
        //public string? diagnosis { get; set; }
        //public string? treatment { get; set; }
        //public int lengthOfStay { get; set; }
        //public string? treatmentDate { get; set; }
        //public int processingCurrencyId { get; set; }
        //public int finalPayableCurrencyId { get; set; }
        //public int createByUserId { get; set; }
        //public string? createDate { get; set; }
        //public int modifyByUserId { get; set; }
        //public string? modifyDate { get; set; }
        //public int insuranceCompanyId { get; set; }
        //public int ailmentId { get; set; }
        //public string? intimationNo { get; set; }
        //public decimal grossAmount { get; set; }
        //public decimal approvedAmount { get; set; }
        //public decimal rejectedAmount { get; set; }
        //public decimal netAmount { get; set; }
        //public int claimStatus { get; set; }
        public int referredToIns { get; set; }
        public string? status { get; set; }
        public string? stageName { get; set; }
        //public string? caseType { get; set; }
        public string? phmRefNo { get; set; }
        public int visibleExtension { get; set; }
        public int visibleEdit { get; set; }
        //public string? patientStatus { get; set; }
        //public int insuranceStatusId { get; set; }
        public string? insuranceStatus { get; set; }
        public string? note { get; set; }
       // public string? memberId { get; set; }
       // public string? phsfirNo { get; set; }
        public int authorisedSignatory { get; set; }
        //public int groupPolicyId { get; set; }
        //public int enrollmentId { get; set; }
        //public string? employeeCode { get; set; }
        public string? caseStatus { get; set; }
        public string? time { get; set; }
    
}
}
